import subprocess
import sys
from pathlib import Path

def run(cmd):
    """Run a shell command, exit on failure."""
    result = subprocess.run(cmd, shell=False)
    if result.returncode != 0:
        sys.exit(1)

def rename(src: Path, dst: Path):
    """Rename a file from src to dst, overwriting dst if it exists."""
    if dst.exists():
        dst.unlink()
    src.rename(dst)

def main():
    # 1. Create c.c with initial lines
    with open("c.c", "w", encoding="utf-8") as f:
        f.write("//< this file is generated by build.py\n")
        f.write("#include <stdio.h>\n")
        f.write("#include <stdlib.h>\n")

    # 2. Preprocess c-source.c -> tmp.c
    run(["gcc", "-E", "-DPREPROC", "c-source.c", "-o", "tmp.c"])

    # 3. Read tmp.c, filter out # lines and blank lines, append to c.c
    with open("tmp.c", "r", encoding="utf-8") as src, \
         open("c.c", "a", encoding="utf-8") as dst:
        for line in src:
            stripped = line.strip()
            if not stripped:
                continue        # skip blank lines
            if stripped.startswith("#"):
                continue        # skip preprocessor lines
            dst.write(line)

    # 4. Rename tmp.c -> c.c
    rename(Path("tmp.c"), Path("c.c"))

if __name__ == "__main__":
    main()